name: 'Code of conduct compliance through sentiments analysis'
description: 'Analyze sentiments in issues and PRs to identify negative content that may violate your code of conduct.'
inputs:
  gcp_key:
    description: 'Google Cloud Platform API key for accessing the analyzeSentiment API. If not provided, then default sentiment analysis is performed.'
    required: false
outputs:
  sentiment:
    description: 'Information about the sentiment of information. It is up to you to decide weather the score is to low or it is fine.'
  source:
    description: 'Link to the resource that was evaluated.'
  negative:
    description: 'Coma-separated list of words that were identified as bad'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: red