name: 'testing workflow'
# Trigger on release
on: 
  issue_comment:
    types: 
      - created
      - edited
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited
  pull_request_review:
    types:
      - submitted
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
jobs:
  test:
    name: Checking sentiments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check sentiment
        uses: ./
        id: sentiments
        with:
          gcp_key: ${{ secrets.GCP_KEY }} 
      - name: Echo sentiment
        run: > 
          echo 'Sentiment: ${{steps.sentiments.outputs.sentiment}}'
          echo 'Source: ${{steps.sentiments.outputs.source}}'
          echo 'Negative words: ${{steps.sentiments.outputs.negative}}'
      - uses: someimportantcompany/github-actions-slack-message@v1
        if: steps.sentiments.outputs.sentiment < 0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: Here ${{steps.sentiments.outputs.source}} you can find a potential negative text that requires your attention as the sentiment analysis score is ${{steps.sentiments.outputs.sentiment}}
          color: failure